class ThemeSize {
  static const double containerPadding = 15;// 每个模块之间的内边距和外边距
  static const double columnPadding = 20;// 上下边距
  static const double middleRadius = 10;// 圆角大小
  static const double textareaHeight = 150;// 多行文本框的高度
  static const double bigRadius = 20;// 圆角大小
  static const double superRadius = 30;// 加大版圆角
  static const double minBtnRadius = 5;// 小圆角
  static const double middleBtnWidth = 70;// 中等按钮宽度
  static const double middleBtnHeight = 35;// 中等按钮高度
  static const double swiperHeight = 200; // 轮播高度
  static const double movieWidth = 150; // 电影图片宽度
  static const double movieHeight = 200;// 电影图片高度
  static const double modualHeight = 250;// 模块的高度
  static const double bigIcon = 40;// 大图标
  static const double middleIcon = 30;// 中等图标
  static const double playIcon = 25;// 中等图标
  static const double navigationIcon = 30;// 导航图标
  static const double smallIcon = 20;// 中等图标
  static const double miniIcon = 15;// 超小图片
  static const double smallMargin = 10;//小边距
  static const double miniMargin = 5;// 超小边距
  static const double smallFontSize = 14;//常规字体
  static const double middleFontSize = 16;//常规字体
  static const double bigFontSize = 20;// 大标题字体
  static const double smallAvater = 30;// 小头像
  static const double middleAvater = 50;// 中等头像
  static const double bigAvater = 60;// 大头像
  static const double borderWidth = 1;// 边框大小
  static const double buttonHeight = 40;//按钮大小
  static const int crossAxisCount = 5;// 网格布局每行元素个数
  static const double childAspectRatio = 1.6;// 网格布局宽高比例
  static const int pageSize = 20;// 每页显示大小
  static const double minPlayIcon = 80;// 音乐播放器圈圈大小
  static const double menuWidth = 180;// 弹出点赞和评论菜单的宽度
  static const double menuHeight = 40;// 弹出点赞和评论菜单的高度
  static const double bottomBarHeight = 85;// 底部导航条高度
  static const double borderSize = 3;
  static const double opacity = 0.5;// 图标透明度
}